### ISSUE TITLE
U-Boot for Radxa CM3 IO misses some files

### ISSUE THREAD

**Issue by a1batross** [radxa/meta-radxa#24]
u-boot-radxa-cm3-io.bb references boot.cmd and uEnv.txt https://github.com/radxa/meta-radxa/blob/dunfell/recipes-bsp/u-boot/u-boot-radxa-cm3-io.bb#L13-L14

But these files do not present here https://github.com/radxa/meta-radxa/tree/dunfell/recipes-bsp/u-boot/files/radxa-cm3-io-rk3566

**Comment by RadxaStephen** [comment]
I will add these two files.

**Comment by floion** [comment]
Hi @RadxaStephen any progress for adding these missing files?

**Comment by floion** [comment]
They have been added with this commit: https://github.com/radxa/meta-radxa/commit/ca2a453207c162264313850296310b4b6a457a9e

**Comment by floion** [comment]
@a1batross I guess you can close this issue
