### ISSUE TITLE
U-Boot for Radxa CM3 IO overrides do_compile, resulting in non-buildable recipe

### ISSUE THREAD

**Issue by a1batross** [radxa/meta-radxa#25]
This function should probably not be empty. If I remove do_compile, u-boot compiles successfully, as generic do_compile from u-boot.inc takes place.

https://github.com/radxa/meta-radxa/blob/dunfell/recipes-bsp/u-boot/u-boot-radxa-cm3-io.bb#L21

**Comment by floion** [comment]
Should be fixed by https://github.com/radxa/meta-radxa/pull/26
