### ISSUE TITLE
ROCK 4 SE support

### ISSUE THREAD

**Issue by floion** [radxa/meta-radxa#35]
Hi, will you be supporting the ROCK 4 SE anytime soon?

Thank you!

**Comment by RadxaYuntian** [comment]
I don't think we have any official plan for Yocto support. @jack-ma for clarification.

**Comment by jack-ma** [comment]
Let's put this on the todo list.

**Comment by przemoch-dev** [comment]
Any update here?

**Comment by RadxaYuntian** [comment]
It is supported in our latest Yocto repo: https://github.com/radxa/meta-rockchip/blob/kirkstone-radxa/conf/machine/rockchip-rk3399-rock-4se.conf
