### ISSUE TITLE
Yocto ROCK 5 support

### ISSUE THREAD

**Issue by nickbetteridge** [radxa/meta-radxa#37]
Hi, will you be supporting the ROCK 5 anytime soon? @jack-ma, could you possibly please add this to the to-do list as well?

Would be very grateful if you could do this

Thanks!

**Comment by slaesh** [comment]
this would be great. we could gain balena support too then

https://github.com/balena-os/balena-radxa/issues/221

**Comment by RadxaYuntian** [comment]
See https://github.com/radxa/meta-rockchip/blob/kirkstone-radxa/conf/machine/rockchip-rk3588-rock-5b.conf
